### PR TITLE
Created Provider that receives logEntry to provide parameters

### PR DESCRIPTION
**Pull request by cleciusjm**
Add ParametrizedStructuredParameterProvider to provide way do get contextualized params

with this interface some params can be generated base in Log entry, like loggerName param

This allow usage like this sample:

```
@Singleton
@Unremovable
public class LogCustomizer implements ParametrizedStructuredParameterProvider {

    @Override
    public StructuredParameter getParameter(ExtLogRecord logEntry) {
        var b = createObjectBuilder()
                .add("thread", currentThread().getName())
                .add("logger", logEntry.getLoggerName());
        return () -> b;
    }

}
```

### CODE REVIEW

**Comment by benkard** [comment]
Hi and thank you for your contribution!  I’m on vacation, so I will have a closer look when I’m back.

Some comments in the meantime: 

- It would be nice if we could (in a backward-compatible way) add this to the existing interfaces rather than introducing new ones. 
- In the interest of forward-compatibility, it may be a good idea to define a custom context class that contains only what is actually useful and what we explicitly decide we want to expose to providers instead of passing an ExtLogRecord (which is both more than the use case calls for and less extensible).

**Comment by cleciusjm** [comment]
Hi thanks for response.
1. backward compatibility was the main reason to add this as another interface.
2. this could be a good option, but there is many ways to interact with ExtLogRecord, and there is possibility to change this in future?

The idea to separate interfaces is to expose more of intern capabilities keeping the simple mode with already existing interface.

My interface is a second level of interaction, more coupled (and less future prone), but more powerful

**Comment by benkard** [comment]
I have prepared a change that I believe is in line with what you are trying to achieve, largely backward-compatible, and with a smaller API surface: https://gerrit.benkard.de/c/quarkus-googlecloud-jsonlogging/+/4161

@cleciusjm, could you have a look and let me know if it serves your use case, please?

**Comment by benkard** [comment]
@cleciusjm, by the way, I cherry-picked your on/off toggle configuration change, the idea of which I like very much: https://github.com/benkard/quarkus-googlecloud-jsonlogging/commit/5303673160fb8a52102a55774eb99dae1ebf5eda

**Comment by cleciusjm** [comment]
Sorry about the delay on response @benkard, nice to see this toggle is already available.

About the change with params, it's a good solution and low coupled, i'll check my usage here and tell you if some param is missing, but in first view, this solve my problem.

**Comment by benkard** [comment]
Since it looks like you didn’t find anything missing, I’m closing this PR.  Feel free to open a new one.

**Pull request closed without merging**
